D:\llama_server\llama-server.exe `
  --alias Gemma4-12B-mtp-qat-UD `
  -m "I:\models\unsloth\gemma-4-12B-it-qat-GGUF\gemma-4-12B-it-qat-UD-Q4_K_XL.gguf" `
  --model-draft "I:\models\unsloth\gemma-4-12B-it-qat-GGUF\gemma-4-12B-it-qat-assistant-MTP-Q8_0.gguf" `
  --spec-type draft-mtp `
  --spec-draft-n-max 4 `
  --parallel 1 `
  --verbosity 4 `
  --ctx-size 164000 `
  --temp 0.4 `
  --top-p 0.95 `
  --top-k 64 `
  -ngl 999 `
  -fa on `
  --chat-template-kwargs '{\"enable_thinking\":false}'