D:llama_server\llama-server.exe `
  --alias qwen36-MTP `
  -m "I:\models\unsloth\Qwen3.6-35B-A3B-MTP-GGUF\Qwen3.6-35B-A3B-UD-Q4_K_M.gguf" `
  -ngl 999 `
  --cache-type-k q8_0 `
  --cache-type-v q8_0 `
  -t 12 `
  --parallel 1 `
  -ncmoe 25 `
  --no-mmap `
  -c 65536 `
  --spec-type draft-mtp `
  --spec-draft-n-max 2 `
  --spec-type ngram-mod `
  --verbosity 3 `
  --flash-attn on `
  --reasoning off `
  --reasoning-budget 0 `
  --no-mmproj